version: '3'
services:
  neo4j:
    image: neo4j:4.1
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /Users/dusen/Dev/docker/neo4j/conf:/conf
      - /Users/dusen/Dev/docker/neo4j/data:/data
      - /Users/dusen/Dev/docker/neo4j/import:/import
      - /Users/dusen/Dev/docker/neo4j/logs:/logs
      - /Users/dusen/Dev/docker/neo4j/plugins:/plugins
    environment: 
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=4G
      - NEO4J_dbms.memory.heap.initial_size=4G
      - NEO4J_dbms_memory_heap_max__size=4G
