version: '3'
services:
  postgres:
    image: postgres:11
    container_name: postgres11
    volumes:
      - ~/Dev/docker/postgres/data:/var/lib/postgresql/data
      - ~/Documents/github.com/ldbc:/root/ldbc
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
